stages:
  - trigger

trigger-backend:
  stage: trigger
  rules:
    - changes:
        - backend/**/*
    - when: always
  trigger:
    project: stug-appen/backend
    branch: master

trigger-frontend:
  stage: trigger
  rules:
    - changes:
        - frontend/**/*
    - when: always
  trigger:
    project: stug-appen/frontend
    branch: master
