stages:
  - clone
  - build
  - push

variables:
  CI_REGISTRY: "docker.io/svesk/stug-appen"
  CI_REGISTRY_USER: "svesk"
  CI_REGISTRY_PASSWORD: "Sebb24330!!?"
  IMAGE_TAG: "stug-api"
  REPOSITORY_URL: "https://github.com/Kapsylen/stug-appen.git"
  BRANCH: "master"

clone:
  stage: clone
  script:
    - echo "Cloning repository..."
    - git clone --branch "$BRANCH" "$REPOSITORY_URL" app
  artifacts:
    paths:
      - app

build:
  stage: build
  image: maven:latest
  dependencies:
    - clone
  script:
    - cd backend
    - echo "Listing directory contents..."
    - ls -la
    - echo "Building Maven project..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

docker:
  stage: push
  image: docker:24
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build
  script:
    - cd backend
    - echo "Building Docker image..."
    - docker build -t "$CI_REGISTRY":"$IMAGE_TAG" .
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin
    - echo "Pushing Docker image..."
    - docker push "$CI_REGISTRY":"$IMAGE_TAG"
