stages:
  - git_clone
  - build_and_push

variables:
  REPO_URL: "https://github.com/Kapsylen/stug-appen.git"
  REPO_BRANCH: "master"
  CI_REGISTRY: "docker.io/svesk/stug-appen"
  IMAGE_NAME: "$CI_REGISTRY:$IMAGE_TAG"
  APP_DIR: "app/backend"
  IMAGE_TAG: "stug-api"

#  REPO_URL: "https://github.com/Kapsylen/stug-appen.git"
#  REPO_BRANCH: "master"
#  CI_REGISTRY: "docker.io/svesk/stug-appen"
#  IMAGE_NAME: "$CI_REGISTRY:$IMAGE_TAG"
#  APP_DIR: "frontend"
#  IMAGE_TAG: "stug-web"

clone:
  stage: git_clone
  script:
    - echo "Cloning repository..."
    - git clone --branch "$REPO_BRANCH" "$REPO_URL" app
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
  artifacts:
    paths:
      - app

build:
  stage: build_and_push
  image: docker:24
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - clone
  before_script:
    - echo "Logging into Docker registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin
  script:
    - echo "Building Docker image..."
    - cd $APP_DIR
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - master
