stages:
  - trigger

trigger-backend:
  stage: trigger
  rules:
    - changes:
        - backend/**/*
  trigger:
    project: stug-appen/backend
    branch: master

trigger-frontend:
  stage: trigger
  rules:
    - changes:
        - frontend/**/*
  trigger:
    project: stug-appen/frontend
    branch: master