stages:
  - build
  - push
  - deploy

variables:
  CI_REGISTRY: "docker.io/svesk/stug-appen"
  CI_REGISTRY_USER: "svesk"
  CI_REGISTRY_PASSWORD: "Sebb24330!!?"
  IMAGE_TAG: "stug-api"
  CI_COMMIT_REF_NAME: "master"
  REPOSITORY_URL: "https://github.com/Kapsylen/stug-appen.git"

build:
  stage: build
  image: docker:24
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - echo "This job runs when pushing to master"
  only:
    - master

  script:
    - git clone --branch "$CI_COMMIT_REF_NAME" "$REPOSITORY_URL" app
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - cd app/backend
    - ls -la
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY":"$IMAGE_TAG" .
    - docker push "$CI_REGISTRY":"$IMAGE_TAG"