services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - app-net
    volumes:
      - ./keycloak-config/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
  postgres-db:
    image: postgres:15
    container_name: stug-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: openjdk:21-jdk-slim
    container_name: stug-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/appdb
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8181:8181"
    depends_on:
      - postgres-db
      - keycloak
    networks:
      - app-net
  frontend:
    image: node:20.19-slim
    container_name: stug-appen
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/stug-appen
    environment:
      - NODE_ENV=development
      - ROLLUP_SKIP_NODEJS=true

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:


