kind: Deployment
apiVersion: apps/v1
metadata:
  name: stug-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stug-web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stug-web
    spec:
      containers:
        - name: container
          image: 'docker.io/svesk/stug-appen:stug-web'
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: stug-web-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

