spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak-angular-sandbox
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://postgres-db:5432/appdb
    username: appuser
    password: apppassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  auth:
    converter:
      resource-id: stug-api-client
      principle-attribute: preferred_username


server:
  port: 8181
